# Generated by Django 5.0.1 on 2024-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0002_vote_delete_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.IntegerField(),
        ),
    ]
