# Generated by Django 5.0.1 on 2024-03-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0003_alter_vote_vote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='birth',
        ),
    ]
